#%RAML 1.0
---
title: hello demo API
baseUri: /api/:version
baseUriParameters:
  host:
    description: 这个host 不一定啊
    enum: ['baidu1.com', 'baidu2.com']
version: v1
mediaType: application/json

# 安全设置
securitySchemes: !include ./raml/securitySchemes.raml

# 自定义资源 types，类似于资源模板，指定 type 可以减少代码，还可以覆盖模板
resourceTypes: !include ./raml/resourceTypes.raml

# 相当于数据类型
types: !include ./raml/types.raml

# header 描述信息，可以通过 is 指令添加到资源，如，is: [ chargeable ]
traits:
  chargeable:
    headers:
      X-Auth-Token:
        type: array
        description: |
          A department code to be charged.
          Multiple of such headers are allowed.
        pattern: ^\d+\-\w+$
        example: 230-OCTO
  traceable:
    headers:
      X-Tracker:
        description: A code to track API calls end to end
        pattern: ^\w{16}$
        example: abcdefghijklmnop

# 用户
/users:
  /:user_id: !include ./raml/api/users/books/books.raml

/song: !include ./raml/api/song/song.raml
