/:
  get:
    description: 商品列表
    queryParameters:
      isStar:
        description: 是否精选
        type: boolean
        required: false
        example: true
    responses:
      200:
        body:
          type: Product[]
          example: !include ./products_200.json

/:id:
  get:
    description: 商品详情
    queryParameters:
      id:
        type: string
        required: true
        description: product id
    responses:
      200:
        body:
          type: Product
          example: !include ./product_200.json
