
oauth_token:
  description: |
    此接口需要登录
  type: x-xxxx-custom
  describedBy:
    headers:
      token:
        description: |
          必须携带 32 位 `token` 字符串
        type: string
    responses:
      401:
        description: |
          没有携带 `token` 或者 `token` 过期则返回 `401`
        body:
          example: |
            {
              "code": 401,
              "message": "请登录"
            }
