
# type: collection
description: this is song url
get:
  (test):
  description: !include ./description.md
  queryParameters:
    a:
      description: "this is a param"
      required: true
      minLength: 3
  responses:
    200:
      body:
        application/json:
          example:
            value: # needs to be declared since instance contains a 'value' property
              - name: A User
                userId: "111"
                kind: user
              - name: An Employee
                employeeId: "222"
                kind: employee
